#!/usr/bin/env bash
# name: archlinux_package_diagnose_002.sh
# version: 0.1.0
# status: PROPOSAL_ONLY
# purpose: Read-only Arch Linux package-management diagnostic snapshot
# platform: Arch Linux
# shell: bash
# risk: LOW; read-only commands only
# root required: no, but some checks report less detail without root
# network required: no
# destructive: no
# backup: not required for read-only execution
# rollback: none; script does not modify system state
# validation: review stdout for package-manager, keyring, cache, pacnew and build-tool state
# source/context: ARCHLINUX-PACKAGES-002

set -u

run() {
  printf '\n### %s\n' "$*"
  "$@" 2>&1 || printf 'command failed with exit=%s\n' "$?"
}

printf 'Arch Linux package diagnostic snapshot\n'
printf 'Generated by proposal script; redact hostnames/usernames/private paths before storage.\n'

run uname -a
run pacman --version
run pacman -Q pacman archlinux-keyring pacman-contrib
run pacman-conf --config /etc/pacman.conf
run pacman -Qkk pacman archlinux-keyring
run ls -ld /var/lib/pacman /var/cache/pacman/pkg /etc/pacman.d/gnupg

if command -v timedatectl >/dev/null 2>&1; then
  run timedatectl status
fi

if command -v pacman-key >/dev/null 2>&1; then
  printf '\n### pacman-key --list-keys first 80 lines\n'
  pacman-key --list-keys 2>&1 | sed -n '1,80p'
fi

if command -v paccache >/dev/null 2>&1; then
  run du -sh /var/cache/pacman/pkg
  run paccache -d
else
  printf '\n### paccache missing\nInstall pacman-contrib for paccache.\n'
fi

if command -v pacdiff >/dev/null 2>&1; then
  run pacdiff --output
else
  printf '\n### pacdiff missing\nInstall pacman-contrib for pacdiff.\n'
fi

printf '\n### pacnew/pacsave/pacorig candidates under /etc\n'
find /etc \( -name '*.pacnew' -o -name '*.pacsave' -o -name '*.pacorig' \) -print 2>/dev/null | sort || true

if [ -f PKGBUILD ] && command -v makepkg >/dev/null 2>&1; then
  run grep -E '^(pkgname|pkgver|pkgrel|arch)=' PKGBUILD
  run makepkg --printsrcinfo
  run makepkg --packagelist
else
  printf '\n### makepkg/PKGBUILD checks skipped\nRun inside a PKGBUILD directory to enable build diagnostics.\n'
fi
